name: Deploy Glue Job

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Debug folder structure
        run: |
          echo "Repo root:"
          ls -la
          echo "src contents:"
          ls -la src
          echo "src tree:"
          ls -R src

      # Cria o zip apenas com as libs (sem o entrypoint main.py)
      - name: Build hv_pipeline.zip
        run: |
          set -e
          test -f src/main.py

          rm -f hv_pipeline.zip

          cd src
          zip -r ../hv_pipeline.zip bronze silver gold common \
            -x "__pycache__/*" \
            -x "*.pyc"

      - name: Upload hv_pipeline.zip to S3
        run: |
          aws s3 cp hv_pipeline.zip s3://hv-challenge/scripts/hv_pipeline.zip

      - name: Upload main.py to S3
        run: |
          aws s3 cp src/main.py s3://hv-challenge/scripts/main.py